
package loginreg;

import Admin.Admindashb;
import Userdashboard.userb;
import config.Session;
import config.dbconnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GUI extends javax.swing.JFrame {

 /**
  * Creates new form GUI
  */
 public GUI() {
      initComponents(); 
 }
 
 
 static String status;
 static String type;
 
public static boolean loginAcc(String username, String password) { 
    dbconnector connector = new dbconnector();

    try {
        // Hash the password entered by the user
        String hashedPassword = passwordHasher.hashPassword(password);

        // Query the database for the username and hashed password
        String query = "SELECT * FROM tbl_user WHERE u_username = ? AND u_password = ?";
        PreparedStatement pstmt = connector.getConnection().prepareStatement(query);
        pstmt.setString(1, username);
        pstmt.setString(2, hashedPassword); // Use the hashed password for comparison
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            // Store user data in the Session
            Session sess = Session.getInstance();
            sess.setUid(resultSet.getInt("u_id"));
            sess.setFname(resultSet.getString("u_fname"));
            sess.setLname(resultSet.getString("u_lname"));
            sess.setEmail(resultSet.getString("u_email"));
            sess.setUsername(resultSet.getString("u_username"));
            sess.setType(resultSet.getString("u_type"));
            sess.setStatus(resultSet.getString("u_status"));

            System.out.println("Login successful. User ID: " + sess.getUid());
            return true;
        } else {
            System.out.println("No matching user found.");
            return false; // No matching user found
        }
    } catch (SQLException ex) {
        System.out.println("Database Error: " + ex.getMessage());
        return false;
    } catch (NoSuchAlgorithmException ex) {
        System.out.println("Password Hashing Error: " + ex.getMessage());
        return false;
    }
}

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  right = new javax.swing.JPanel();
  Left = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  User = new javax.swing.JLabel();
  Password = new javax.swing.JLabel();
  user = new javax.swing.JTextField();
  pass = new javax.swing.JPasswordField();
  Login = new javax.swing.JButton();
  registration = new javax.swing.JLabel();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

  right.setBackground(new java.awt.Color(88, 72, 72));

  Left.setBackground(new java.awt.Color(236, 45, 45));

  javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
  Left.setLayout(LeftLayout);
  LeftLayout.setHorizontalGroup(
   LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 138, Short.MAX_VALUE)
  );
  LeftLayout.setVerticalGroup(
   LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 400, Short.MAX_VALUE)
  );

  jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
  jLabel1.setForeground(new java.awt.Color(204, 204, 204));
  jLabel1.setText("LOGIN");

  User.setBackground(new java.awt.Color(204, 204, 204));
  User.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  User.setForeground(new java.awt.Color(204, 204, 204));
  User.setText("User");

  Password.setBackground(new java.awt.Color(204, 204, 204));
  Password.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  Password.setForeground(new java.awt.Color(204, 204, 204));
  Password.setText("Password");

  user.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    userActionPerformed(evt);
   }
  });

  Login.setBackground(new java.awt.Color(236, 45, 45));
  Login.setText("Login");
  Login.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    LoginMouseClicked(evt);
   }
  });
  Login.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    LoginActionPerformed(evt);
   }
  });

  registration.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
  registration.setForeground(new java.awt.Color(204, 204, 204));
  registration.setText("Click here to Create an account..");
  registration.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    registrationMouseClicked(evt);
   }
  });

  javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
  right.setLayout(rightLayout);
  rightLayout.setHorizontalGroup(
   rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(rightLayout.createSequentialGroup()
    .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(rightLayout.createSequentialGroup()
      .addGap(154, 154, 154)
      .addComponent(jLabel1))
     .addGroup(rightLayout.createSequentialGroup()
      .addGap(79, 79, 79)
      .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
       .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
       .addComponent(User)
       .addComponent(Password)
       .addComponent(Login)
       .addComponent(registration))))
    .addContainerGap(127, Short.MAX_VALUE))
  );
  rightLayout.setVerticalGroup(
   rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addGroup(rightLayout.createSequentialGroup()
    .addGap(77, 77, 77)
    .addComponent(jLabel1)
    .addGap(18, 18, 18)
    .addComponent(User)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addComponent(Password)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(registration)
    .addContainerGap(74, Short.MAX_VALUE))
  );

  getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

 private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_userActionPerformed

 private void registrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseClicked
   new registration().setVisible(true);
        this.dispose(); 
 }//GEN-LAST:event_registrationMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
Login.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
         LoginMouseClicked(evt);
    }
});
    }//GEN-LAST:event_LoginMouseClicked

 private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
  
      String username = user.getText();
    String password = new String(pass.getPassword());

    System.out.println("Username: " + username);
    System.out.println("Password: " + password);

    if (loginAcc(username, password)) {
        Session sess = Session.getInstance();
        String status = sess.getStatus(); // Get the user's status (Active or Pending)
        String type = sess.getType(); // Get the user's type (admin or user)

        if (status.equals("Active")) {
            if (type.equals("admin")) {
                // Redirect to admin dashboard
                Admindashb ads = new Admindashb();
                ads.setVisible(true);
                this.dispose();
            } else if (type.equals("user")) {
                // Redirect to user dashboard
                userb uds = new userb();
                uds.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid account type. Contact support.");
            }
        } else if (status.equals("Pending")) {
            // Prevent login for Pending accounts
            JOptionPane.showMessageDialog(null, "Contact Admin. Account is Inactive.");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid account status. Contact support.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Login failed. Please try again.");
    }
 }//GEN-LAST:event_LoginActionPerformed

 
 public static void main(String args[]) {
  
  
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new GUI().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JPanel Left;
 private javax.swing.JButton Login;
 private javax.swing.JLabel Password;
 private javax.swing.JLabel User;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JPasswordField pass;
 private javax.swing.JLabel registration;
 private javax.swing.JPanel right;
 private javax.swing.JTextField user;
 // End of variables declaration//GEN-END:variables
}
