
package Admin;

import config.Session;
import java.awt.Color;
import javax.swing.JOptionPane;
import loginreg.GUI;


public class Admindashb extends javax.swing.JFrame {
Color navcolor = new Color(240,240,240);
  Color hovercolor = new Color(204,0,0);
  
 public Admindashb() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel1 = new javax.swing.JPanel();
  jPanel2 = new javax.swing.JPanel();
  jPanel3 = new javax.swing.JPanel();
  jPanel6 = new javax.swing.JPanel();
  p_add = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  jPanel11 = new javax.swing.JPanel();
  jPanel14 = new javax.swing.JPanel();
  jPanel4 = new javax.swing.JPanel();
  p_out = new javax.swing.JPanel();
  jLabel2 = new javax.swing.JLabel();
  jPanel5 = new javax.swing.JPanel();
  jButton1 = new javax.swing.JButton();
  acc_name = new javax.swing.JLabel();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  addWindowListener(new java.awt.event.WindowAdapter() {
   public void windowActivated(java.awt.event.WindowEvent evt) {
    formWindowActivated(evt);
   }
  });
  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

  jPanel2.setBackground(new java.awt.Color(51, 51, 51));
  jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

  jPanel3.setBackground(new java.awt.Color(0, 0, 0));

  javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
  jPanel6.setLayout(jPanel6Layout);
  jPanel6Layout.setHorizontalGroup(
   jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 30, Short.MAX_VALUE)
  );
  jPanel6Layout.setVerticalGroup(
   jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 31, Short.MAX_VALUE)
  );

  p_add.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    p_addMouseClicked(evt);
   }
   public void mouseEntered(java.awt.event.MouseEvent evt) {
    p_addMouseEntered(evt);
   }
   public void mouseExited(java.awt.event.MouseEvent evt) {
    p_addMouseExited(evt);
   }
  });

  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-add-users-32.png"))); // NOI18N

  javax.swing.GroupLayout p_addLayout = new javax.swing.GroupLayout(p_add);
  p_add.setLayout(p_addLayout);
  p_addLayout.setHorizontalGroup(
   p_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(p_addLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel1)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  p_addLayout.setVerticalGroup(
   p_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(p_addLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel1)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
  jPanel11.setLayout(jPanel11Layout);
  jPanel11Layout.setHorizontalGroup(
   jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 0, Short.MAX_VALUE)
  );
  jPanel11Layout.setVerticalGroup(
   jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 47, Short.MAX_VALUE)
  );

  javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
  jPanel14.setLayout(jPanel14Layout);
  jPanel14Layout.setHorizontalGroup(
   jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 61, Short.MAX_VALUE)
  );
  jPanel14Layout.setVerticalGroup(
   jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 47, Short.MAX_VALUE)
  );

  javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
  jPanel3.setLayout(jPanel3Layout);
  jPanel3Layout.setHorizontalGroup(
   jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addGroup(jPanel3Layout.createSequentialGroup()
    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(0, 0, Short.MAX_VALUE))
   .addGroup(jPanel3Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
   .addComponent(p_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );
  jPanel3Layout.setVerticalGroup(
   jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel3Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(89, 89, 89)
    .addComponent(p_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(36, 36, 36)
    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(38, 38, 38)
    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap(157, Short.MAX_VALUE))
  );

  jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 510));

  jPanel4.setBackground(new java.awt.Color(102, 102, 102));

  p_out.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    p_outMouseClicked(evt);
   }
   public void mouseEntered(java.awt.event.MouseEvent evt) {
    p_outMouseEntered(evt);
   }
   public void mouseExited(java.awt.event.MouseEvent evt) {
    p_outMouseExited(evt);
   }
  });

  jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-logout-30.png"))); // NOI18N

  javax.swing.GroupLayout p_outLayout = new javax.swing.GroupLayout(p_out);
  p_out.setLayout(p_outLayout);
  p_outLayout.setHorizontalGroup(
   p_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(p_outLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel2)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  p_outLayout.setVerticalGroup(
   p_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(p_outLayout.createSequentialGroup()
    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(0, 11, Short.MAX_VALUE))
  );

  javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
  jPanel4.setLayout(jPanel4Layout);
  jPanel4Layout.setHorizontalGroup(
   jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
    .addContainerGap(460, Short.MAX_VALUE)
    .addComponent(p_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap())
  );
  jPanel4Layout.setVerticalGroup(
   jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
    .addGap(0, 0, Short.MAX_VALUE)
    .addComponent(p_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
  );

  jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 520, 40));

  jPanel5.setBackground(new java.awt.Color(102, 102, 102));

  jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-user-male-48.png"))); // NOI18N
  jButton1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton1ActionPerformed(evt);
   }
  });

  acc_name.setBackground(new java.awt.Color(0, 0, 0));
  acc_name.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
  acc_name.setText("ADMIN");

  javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
  jPanel5.setLayout(jPanel5Layout);
  jPanel5Layout.setHorizontalGroup(
   jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel5Layout.createSequentialGroup()
    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(jPanel5Layout.createSequentialGroup()
      .addGap(19, 19, 19)
      .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(jPanel5Layout.createSequentialGroup()
      .addGap(44, 44, 44)
      .addComponent(acc_name)))
    .addContainerGap(19, Short.MAX_VALUE))
  );
  jPanel5Layout.setVerticalGroup(
   jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel5Layout.createSequentialGroup()
    .addGap(21, 21, 21)
    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(acc_name)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 140));

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  );
  jPanel1Layout.setVerticalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(0, 0, Short.MAX_VALUE))
  );

  getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_jButton1ActionPerformed

 private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      Session sess = Session.getInstance();

    // Check if the user is logged in
    if (sess.getUid() == 0) { // Assuming getUid() returns 0 if no user is logged in
        JOptionPane.showMessageDialog(null, "No account, Please Login First!!!!!!!!!");
        GUI loginGUI = new GUI();
        loginGUI.setVisible(true);
        this.dispose();
    } else {
        // Set the user's first name to the acc_name label
        acc_name.setText(sess.getLname());
       
    }
 }//GEN-LAST:event_formWindowActivated

 private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
  Color navcolor = new Color(240,240,240);
  Color hovercolor = new Color(204,0,0);
  
  p_add.setBackground(hovercolor);
  
 }//GEN-LAST:event_p_addMouseEntered

 private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
 Color navcolor = new Color(240,240,240);
  Color hovercolor = new Color(102,102,102);
  
  p_add.setBackground(navcolor);
  
 }//GEN-LAST:event_p_addMouseExited

 private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
  Userform uf = new Userform();
                uf.setVisible(true);
                this.dispose();
 }//GEN-LAST:event_p_addMouseClicked

 private void p_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_outMouseEntered
 p_out.setBackground(hovercolor);
 }//GEN-LAST:event_p_outMouseEntered

 private void p_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_outMouseExited
 p_out.setBackground(navcolor);
 }//GEN-LAST:event_p_outMouseExited

 private void p_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_outMouseClicked
   int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    // If the user confirms, log out and go back to the login screen
    if (response == JOptionPane.YES_OPTION) {
       
        GUI loginGUI = new GUI();
        loginGUI.setVisible(true);
        this.dispose();
    }
 }//GEN-LAST:event_p_outMouseClicked

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(Admindashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(Admindashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(Admindashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(Admindashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new Admindashb().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JLabel acc_name;
 private javax.swing.JButton jButton1;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JPanel jPanel11;
 private javax.swing.JPanel jPanel14;
 private javax.swing.JPanel jPanel2;
 private javax.swing.JPanel jPanel3;
 private javax.swing.JPanel jPanel4;
 private javax.swing.JPanel jPanel5;
 private javax.swing.JPanel jPanel6;
 private javax.swing.JPanel p_add;
 private javax.swing.JPanel p_out;
 // End of variables declaration//GEN-END:variables
}
