/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import config.dbconnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class updateform extends javax.swing.JFrame {

 public updateform() {
  initComponents();
    uid = new javax.swing.JTextField();
    uid.setEditable(false); // Make uid non-editable
    uid.setVisible(true);   // Ensure it is visible
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  right = new javax.swing.JPanel();
  Left = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  fname = new javax.swing.JLabel();
  Lname = new javax.swing.JLabel();
  a = new javax.swing.JLabel();
  Password = new javax.swing.JLabel();
  User = new javax.swing.JLabel();
  un = new javax.swing.JTextField();
  Cancel = new javax.swing.JButton();
  User1 = new javax.swing.JLabel();
  e = new javax.swing.JTextField();
  num = new javax.swing.JTextField();
  fn = new javax.swing.JTextField();
  ln = new javax.swing.JTextField();
  ut = new javax.swing.JComboBox<>();
  us = new javax.swing.JComboBox<>();
  Password1 = new javax.swing.JLabel();
  Password2 = new javax.swing.JLabel();
  delete = new javax.swing.JButton();
  refresh = new javax.swing.JButton();
  update = new javax.swing.JButton();
  clear = new javax.swing.JButton();
  uid = new javax.swing.JTextField();
  fname1 = new javax.swing.JLabel();
  pass = new javax.swing.JPasswordField();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  right.setBackground(new java.awt.Color(88, 72, 72));

  Left.setBackground(new java.awt.Color(236, 45, 45));

  javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
  Left.setLayout(LeftLayout);
  LeftLayout.setHorizontalGroup(
   LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 243, Short.MAX_VALUE)
  );
  LeftLayout.setVerticalGroup(
   LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 0, Short.MAX_VALUE)
  );

  jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
  jLabel1.setForeground(new java.awt.Color(204, 204, 204));
  jLabel1.setText("Update Form");

  fname.setBackground(new java.awt.Color(204, 204, 204));
  fname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  fname.setForeground(new java.awt.Color(204, 204, 204));
  fname.setText("First Name");

  Lname.setBackground(new java.awt.Color(204, 204, 204));
  Lname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  Lname.setForeground(new java.awt.Color(204, 204, 204));
  Lname.setText("Last Name");

  a.setBackground(new java.awt.Color(204, 204, 204));
  a.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  a.setForeground(new java.awt.Color(204, 204, 204));
  a.setText("Email");

  Password.setBackground(new java.awt.Color(204, 204, 204));
  Password.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  Password.setForeground(new java.awt.Color(204, 204, 204));
  Password.setText("Type");

  User.setBackground(new java.awt.Color(204, 204, 204));
  User.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  User.setForeground(new java.awt.Color(204, 204, 204));
  User.setText("Username");

  un.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    unActionPerformed(evt);
   }
  });

  Cancel.setBackground(new java.awt.Color(236, 45, 45));
  Cancel.setText("Cancel");
  Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    CancelMouseClicked(evt);
   }
  });
  Cancel.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    CancelActionPerformed(evt);
   }
  });

  User1.setBackground(new java.awt.Color(204, 204, 204));
  User1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  User1.setForeground(new java.awt.Color(204, 204, 204));
  User1.setText("Contact number");

  e.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    eActionPerformed(evt);
   }
  });

  num.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    numActionPerformed(evt);
   }
  });

  fn.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    fnActionPerformed(evt);
   }
  });

  ln.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    lnActionPerformed(evt);
   }
  });

  ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "admin" }));
  ut.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    utActionPerformed(evt);
   }
  });

  us.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", " Pending" }));
  us.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    usActionPerformed(evt);
   }
  });

  Password1.setBackground(new java.awt.Color(204, 204, 204));
  Password1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  Password1.setForeground(new java.awt.Color(204, 204, 204));
  Password1.setText("password");

  Password2.setBackground(new java.awt.Color(204, 204, 204));
  Password2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  Password2.setForeground(new java.awt.Color(204, 204, 204));
  Password2.setText("Status");

  delete.setBackground(new java.awt.Color(236, 45, 45));
  delete.setText("Delete");
  delete.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    deleteMouseClicked(evt);
   }
  });
  delete.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    deleteActionPerformed(evt);
   }
  });

  refresh.setBackground(new java.awt.Color(236, 45, 45));
  refresh.setText("Refresh");
  refresh.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    refreshMouseClicked(evt);
   }
  });
  refresh.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    refreshActionPerformed(evt);
   }
  });

  update.setBackground(new java.awt.Color(236, 45, 45));
  update.setText("Update");
  update.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    updateMouseClicked(evt);
   }
  });
  update.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    updateActionPerformed(evt);
   }
  });

  clear.setBackground(new java.awt.Color(236, 45, 45));
  clear.setText("Clear");
  clear.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    clearMouseClicked(evt);
   }
  });
  clear.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    clearActionPerformed(evt);
   }
  });

  uid.setEnabled(false);
  uid.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    uidActionPerformed(evt);
   }
  });

  fname1.setBackground(new java.awt.Color(204, 204, 204));
  fname1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
  fname1.setForeground(new java.awt.Color(204, 204, 204));
  fname1.setText("ID");

  pass.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    passActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
  right.setLayout(rightLayout);
  rightLayout.setHorizontalGroup(
   rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(rightLayout.createSequentialGroup()
    .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(rightLayout.createSequentialGroup()
      .addGap(50, 50, 50)
      .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(rightLayout.createSequentialGroup()
         .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(fname)
          .addComponent(Lname)
          .addComponent(fname1))
         .addGap(10, 10, 10)
         .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(rightLayout.createSequentialGroup()
         .addComponent(User1)
         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
         .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(rightLayout.createSequentialGroup()
         .addComponent(a)
         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
         .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(rightLayout.createSequentialGroup()
         .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(User)
          .addComponent(Password)
          .addComponent(Password2)
          .addComponent(Password1))
         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
         .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(un, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
          .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pass)))
        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rightLayout.createSequentialGroup()
         .addGap(54, 54, 54)
         .addComponent(refresh)))
       .addGroup(rightLayout.createSequentialGroup()
        .addGap(158, 158, 158)
        .addComponent(update)
        .addGap(18, 18, 18)
        .addComponent(delete)
        .addGap(18, 18, 18)
        .addComponent(clear)))
      .addContainerGap(54, Short.MAX_VALUE))
     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
        .addComponent(Cancel)
        .addContainerGap())
       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(151, 151, 151))))))
  );
  rightLayout.setVerticalGroup(
   rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addGroup(rightLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(7, 7, 7)
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
     .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(fname1))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(fname)
     .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(Lname)
     .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(a)
     .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(11, 11, 11)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(User1)
     .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(8, 8, 8)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(User)
     .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(Password1)
     .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(Password)
     .addComponent(ut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(Password2)
     .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
    .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addContainerGap())
  );

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 728, Short.MAX_VALUE)
   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
     .addGap(0, 0, Short.MAX_VALUE)
     .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGap(0, 0, Short.MAX_VALUE)))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 430, Short.MAX_VALUE)
   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
     .addGap(0, 0, Short.MAX_VALUE)
     .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGap(0, 0, Short.MAX_VALUE)))
  );

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

 private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
  clearFields();
  }

  // Method to clear all input fields
  private void clearFields() {
   fn.setText("");
   ln.setText("");
   e.setText("");
   num.setText("");
   un.setText("");
   pass.setText("");
   ut.setSelectedIndex(0);
   us.setSelectedIndex(0);
 }//GEN-LAST:event_clearActionPerformed

 private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
  // TODO add your handling code here:
 }//GEN-LAST:event_clearMouseClicked

 private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
  if (fn.getText().isEmpty() || ln.getText().isEmpty() || e.getText().isEmpty() ||
        un.getText().isEmpty() || pass.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required!");
    } else if (pass.getText().length() < 8) {
        JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long!");
        pass.setText("");
    } else {
        // Debug: Print the u_id value
        System.out.println("Updating user with ID: " + uid.getText());

        dbconnector dbc = new dbconnector();

        // Check for duplicate email or username (excluding the current user)
        if (dbc.isDuplicate(e.getText(), un.getText(), uid.getText())) {
            JOptionPane.showMessageDialog(null, "Email or username already exists!");
            return; // Stop the update process
        }

        // Hash the password (whether it was changed or not)
        String newPassword;
        try {
            newPassword = passwordHasher.hashPassword(pass.getText()); // Hash the password
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(this, "Error hashing password.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Proceed with the update if no duplicates are found
        String query = "UPDATE tbl_user SET " +
            "u_fname = ?, " +
            "u_lname = ?, " +
            "u_email = ?, " +
            "u_username = ?, " +
            "u_password = ?, " +
            "u_type = ?, " +
            "u_status = ? " +
            "WHERE u_id = ?"; // uid is only used in the WHERE clause

        boolean success = dbc.updateData(query,
            fn.getText(),       // u_fname
            ln.getText(),       // u_lname
            e.getText(),        // u_email
            un.getText(),       // u_username
            newPassword,        // u_password (hashed)
            ut.getSelectedItem().toString(), // u_type
            us.getSelectedItem().toString(), // u_status
            uid.getText()       // u_id (used in WHERE clause)
        );

        if (success) {
            JOptionPane.showMessageDialog(null, "User updated successfully!");
            Userform uf = new Userform();
            uf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update user!");
        }
    }
 }//GEN-LAST:event_updateActionPerformed

 private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
  // TODO add your handling code here:
 }//GEN-LAST:event_updateMouseClicked

 private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_refreshActionPerformed

 private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
  // TODO add your handling code here:
 }//GEN-LAST:event_refreshMouseClicked

 private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
   int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to delete this user?", 
        "Confirm Deletion", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        // Get the user ID
        String userId = uid.getText();

        // Check if the user ID is valid
        if (userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No user selected!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Delete the user from the database
        dbconnector dbc = new dbconnector();
        String query = "DELETE FROM tbl_user WHERE u_id = ?";

        boolean success = dbc.deleteData(query, userId);

        if (success) {
            JOptionPane.showMessageDialog(this, "User deleted successfully!");
            Userform uf = new Userform();
            uf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete user!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
 }//GEN-LAST:event_deleteActionPerformed

 private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
  // TODO add your handling code here:
 }//GEN-LAST:event_deleteMouseClicked

 private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_usActionPerformed

 private void utActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_utActionPerformed

 private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_lnActionPerformed

 private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_fnActionPerformed

 private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_numActionPerformed

 private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_eActionPerformed

 private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
  Userform uf = new Userform();
  uf.setVisible(true);
  this.dispose();
 }//GEN-LAST:event_CancelActionPerformed

 private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
  Userform uf = new Userform();
  uf.setVisible(true);
  this.dispose();
 }//GEN-LAST:event_CancelMouseClicked

 private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_unActionPerformed

 private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_uidActionPerformed

 private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_passActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new updateform().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton Cancel;
 private javax.swing.JPanel Left;
 private javax.swing.JLabel Lname;
 private javax.swing.JLabel Password;
 private javax.swing.JLabel Password1;
 private javax.swing.JLabel Password2;
 private javax.swing.JLabel User;
 private javax.swing.JLabel User1;
 private javax.swing.JLabel a;
 private javax.swing.JButton clear;
 private javax.swing.JButton delete;
 public javax.swing.JTextField e;
 public javax.swing.JTextField fn;
 private javax.swing.JLabel fname;
 private javax.swing.JLabel fname1;
 private javax.swing.JLabel jLabel1;
 public javax.swing.JTextField ln;
 public javax.swing.JTextField num;
 public javax.swing.JPasswordField pass;
 private javax.swing.JButton refresh;
 private javax.swing.JPanel right;
 public javax.swing.JTextField uid;
 public javax.swing.JTextField un;
 public javax.swing.JButton update;
 public javax.swing.JComboBox<String> us;
 public javax.swing.JComboBox<String> ut;
 // End of variables declaration//GEN-END:variables

 private boolean duplicateCheck() {
 //To change body of generated methods, choose Tools | Templates.
 

